"""Git operations module."""

from coderecon.adapters.git.errors import (
    AuthenticationError,
    BranchExistsError,
    BranchNotFoundError,
    ConflictError,
    DetachedHeadError,
    DirtyWorkingTreeError,
    GitError,
    NoRebaseInProgressError,
    NoStashEntriesError,
    NotARepositoryError,
    NothingToCommitError,
    RebaseConflictError,
    RebaseError,
    RebaseInProgressError,
    RefNotFoundError,
    RemoteError,
    StashNotFoundError,
    SubmoduleError,
    SubmoduleNotFoundError,
    SubmoduleNotInitializedError,
    UnmergedBranchError,
    WorktreeError,
    WorktreeExistsError,
    WorktreeLockedError,
    WorktreeNotFoundError,
)
from coderecon.adapters.git.models import (
    BlameHunk,
    BlameInfo,
    BranchInfo,
    CommitInfo,
    DiffFile,
    DiffInfo,
    DiffSummary,
    FileDiffSummary,
    MergeAnalysis,
    MergeResult,
    OperationResult,
    PullResult,
    RebaseAction,
    RebasePlan,
    RebaseResult,
    RebaseResultState,
    RebaseStep,
    RefInfo,
    RemoteInfo,
    Signature,
    StashEntry,
    SubmoduleInfo,
    SubmoduleState,
    SubmoduleStatus,
    SubmoduleUpdateResult,
    TagInfo,
    WorktreeInfo,
)
from coderecon.adapters.git.ops import GitOps

__all__ = [
    # Main class
    "GitOps",
    # Models
    "Signature",
    "CommitInfo",
    "BranchInfo",
    "TagInfo",
    "RemoteInfo",
    "DiffFile",
    "DiffInfo",
    "DiffSummary",
    "FileDiffSummary",
    "BlameHunk",
    "BlameInfo",
    "StashEntry",
    "RefInfo",
    "MergeResult",
    "MergeAnalysis",
    "OperationResult",
    "PullResult",
    # Worktree models
    "WorktreeInfo",
    # Submodule models
    "SubmoduleInfo",
    "SubmoduleState",
    "SubmoduleStatus",
    "SubmoduleUpdateResult",
    # Rebase models
    "RebaseAction",
    "RebasePlan",
    "RebaseStep",
    "RebaseResult",
    "RebaseResultState",
    # Errors
    "GitError",
    "NotARepositoryError",
    "RefNotFoundError",
    "BranchExistsError",
    "BranchNotFoundError",
    "ConflictError",
    "DirtyWorkingTreeError",
    "NothingToCommitError",
    "AuthenticationError",
    "RemoteError",
    "StashNotFoundError",
    "NoStashEntriesError",
    "DetachedHeadError",
    "UnmergedBranchError",
    # Worktree errors
    "WorktreeError",
    "WorktreeNotFoundError",
    "WorktreeExistsError",
    "WorktreeLockedError",
    # Submodule errors
    "SubmoduleError",
    "SubmoduleNotFoundError",
    "SubmoduleNotInitializedError",
    # Rebase errors
    "RebaseError",
    "RebaseInProgressError",
    "NoRebaseInProgressError",
    "RebaseConflictError",
]
