"""Internal git constants - status flags and mode identifiers."""

from __future__ import annotations

# Working tree status flags (bitmask, matching pygit2 layout for API compatibility)
STATUS_WT_NEW = 0x0080
STATUS_WT_MODIFIED = 0x0100
STATUS_WT_DELETED = 0x0200

# Index status flags
STATUS_INDEX_NEW = 0x0001
STATUS_INDEX_MODIFIED = 0x0002
STATUS_INDEX_DELETED = 0x0004

# Reset modes
RESET_SOFT = "soft"
RESET_MIXED = "mixed"
RESET_HARD = "hard"

# Merge analysis flags (bitmask)
MERGE_UP_TO_DATE = 0x01
MERGE_FASTFORWARD = 0x02
MERGE_NORMAL = 0x04

# Repository state constants (matching git conventions)
GIT_REPOSITORY_STATE_NONE = 0
GIT_REPOSITORY_STATE_MERGE = 1
GIT_REPOSITORY_STATE_REVERT = 2
GIT_REPOSITORY_STATE_REVERT_SEQUENCE = 3
GIT_REPOSITORY_STATE_CHERRYPICK = 4
GIT_REPOSITORY_STATE_CHERRYPICK_SEQUENCE = 5
GIT_REPOSITORY_STATE_BISECT = 6
GIT_REPOSITORY_STATE_REBASE = 7
GIT_REPOSITORY_STATE_REBASE_INTERACTIVE = 8
GIT_REPOSITORY_STATE_REBASE_MERGE = 9
GIT_REPOSITORY_STATE_APPLY_MAILBOX = 10
GIT_REPOSITORY_STATE_APPLY_MAILBOX_OR_REBASE = 11
